- name: "kind: breaking-change"
  description: ""
  color: e11d21
  emoji: "💔"
- name: "kind: bug"
  description: Categorizes issue or PR as related to a bug.
  color: e11d21
  emoji: "🐛"
- name: 'kind: generation-issue'
  description: Categorizes issue or PR as related to the generation pipeline.
  color: e11d21
  emoji: "⚙️"
- name: "kind: documentation"
  description: Categorizes issue or PR as related to documentation.
  color: d4c5f9
  emoji: "📚"
- name: "kind: enhancement"
  description: Categorizes issue or PR as related to improving an existing feature.
  color: d4c5f9
  emoji: "✨"
- name: "kind: failing-test"
  description: Categorizes issue or PR as related to a consistently or frequently failing test.
  color: e11d21
  emoji: "❌"
- name: "kind: flakey"
  description: Categorizes issue or PR as related to a flaky test.
  color: e11d21
  emoji: "🎲"
- name: "kind: regression"
  description: Categorizes issue or PR as related to a regression from a prior release.
  color: e11d21
  emoji: "⏪"
- name: "kind: support"
  description: Categorizes issue or PR as related to user support.
  color: e11d21
  emoji: "🤝"
- name: "lifecycle: stale"
  description: ""
  color: e11d21
  emoji: "⏳"
- name: "likelihood: all"
  description: Categorizes issue or PR as impacting all users.
  color: F7D2B6
  emoji: "🌍"
- name: "likelihood: few"
  description: Categorizes issue or PR as impacting a small portion of users.
  color: F7D2B6
  emoji: "👥"
- name: "likelihood: low"
  description: Categorizes issue or PR as impacting a low portion of users.
  color: F7D2B6
  emoji: "📉"
- name: "likelihood: many"
  description: Categorizes issue or PR as impacting many users.
  color: F7D2B6
  emoji: "👨‍👩‍👧‍👦"
- name: "likelihood: most"
  description: Categorizes issue or PR as impacting most users.
  color: F7D2B6
  emoji: "🚀"
- name: "needs-triage"
  description: "Indicates an issue or PR lacks a `triage: foo` label and requires one."
  color: ef9ed3
  emoji: "🔍"
- name: "service: access"
  description: Categorizes issue or PR as related to the Access service.
  color: 98D063
  emoji: "🔑"
- name: "service: api-shield"
  description: Categorizes issue or PR as related to the API shield service.
  color: 98D063
  emoji: "🛡️"
- name: "workflow: needs-review"
  description: Indicates an issue or PR needs review or feedback.
  color: 006b75
  emoji: "👀"
- name: "workflow: synced"
  description: ""
  color: 006b75
  emoji: "🔄"

# Add similar emoji assignments to other labels as needed.
